# This is an example file to customize a node running the provisioning joining node appliation

# Hex array must start with 0x otherwise it is treated as a string.

# Format is:
#
# provisioning :
#    device_uid: (16 bytes string, Representing the UID of the device to be provisioned)
#    device_uid_type: (1 byte string, Representing the UID type of device_uid)
#    authenticator_uid: (16 bytes string, Representing the UID of the authenticator)
#    authenticator_uid_type: (1 byte string, Representing the UID type of authenticator_uid)
#    Instead of specifying uid components individually, you can specify the whole uid as follows:
#    uid: (34 bytes string, [0:1 device_uid_type][1:16 device_uid][16:17 authenticator_uid_type][17:33 authenticator_uid])
#    factory_key : (32 bytes string, [0:15 Auth key][16:31 Enc Key]) Needed for secured method.
#    method : (Unsecured:0, Secured:1, Extended:3) Ex: 0

provisioning:
    uid: 0x58 0xc8 0x12 0xad 0x37 0xe8 0x36 0x4a 0xa1 0x1f 0x1c 0xbc 0x63 0x3e 0x8e 0x34
    factory_key : 0x00 0x01 0x02 0x03 0x04 0x05 0x06 0x07 0x08 0X09 0X0A 0X0B 0X0C 0X0D 0X0E 0X0F 0x00 0x01 0x02 0x03 0x04 0x05 0x06 0x07 0x08 0X09 0X0A 0X0B 0X0C 0X0D 0X0E 0X0F
    method: 0x01
